extends RefCounted
class_name MazePointLocalization

const DEFAULT_LANGUAGE := "en"

const LANGUAGES := [
	{"code": "en", "name": "English"},
	{"code": "zh_CN", "name": "简体中文"},
	{"code": "hi", "name": "हिन्दी"},
	{"code": "es", "name": "Español"},
	{"code": "ar", "name": "العربية"},
	{"code": "fr", "name": "Français"},
	{"code": "pt_BR", "name": "Português (Brasil)"},
	{"code": "de", "name": "Deutsch"},
	{"code": "ja", "name": "日本語"},
	{"code": "ko", "name": "한국어"},
]

const STRINGS := {
	"en": {
		"GAME_TITLE": "MAZE POINT",
		"BY": "by",
		"LEVEL_STATUS": "LEVEL %d  |  %d / %d",
		"MOVES": "%d MOVES",
		"LEVEL_CLEAR": "LEVEL CLEAR",
		"TOTAL_MOVES": "TOTAL %d / %d  |  MOVES %d",
		"OPTIMAL": "OPTIMAL %d",
		"RETRIES": "RETRIES %d",
		"NEXT": "NEXT",
		"RETRY": "RETRY",
		"RUN_OVER": "RUN OVER",
		"SCORE": "SCORE %d",
		"LEVELS": "LEVELS %d",
		"STARS": "STARS %d",
		"PAUSED": "PAUSED",
		"RESUME": "RESUME",
		"START": "START",
		"NEW_RUN": "NEW RUN",
		"END_RUN": "END RUN",
		"INVERT": "INVERT",
		"MUSIC": "MUSIC",
		"SFX": "SFX",
		"BEST_SCORE_NONE": "BEST SCORE --",
		"BEST_SCORE": "BEST SCORE %d",
		"TRY_AGAIN": "TRY AGAIN",
		"LOADING": "LOADING",
		"BUILDING_RUN": "BUILDING NEW RUN",
		"LANGUAGE": "LANGUAGE",
		"LANGUAGE_VALUE": "LANGUAGE: %s",
	},
	"zh_CN": {
		"GAME_TITLE": "MAZE POINT",
		"BY": "作者",
		"LEVEL_STATUS": "关卡 %d  |  %d / %d",
		"MOVES": "%d 步",
		"LEVEL_CLEAR": "过关",
		"TOTAL_MOVES": "总计 %d / %d  |  步数 %d",
		"OPTIMAL": "最优 %d",
		"RETRIES": "重试 %d",
		"NEXT": "下一关",
		"RETRY": "重试",
		"RUN_OVER": "本轮结束",
		"SCORE": "得分 %d",
		"LEVELS": "关卡 %d",
		"STARS": "星星 %d",
		"PAUSED": "已暂停",
		"RESUME": "继续",
		"START": "开始",
		"NEW_RUN": "新一轮",
		"END_RUN": "结束本轮",
		"INVERT": "反转颜色",
		"MUSIC": "音乐",
		"SFX": "音效",
		"BEST_SCORE_NONE": "最佳分数 --",
		"BEST_SCORE": "最佳分数 %d",
		"TRY_AGAIN": "再试一次",
		"LOADING": "加载中",
		"BUILDING_RUN": "正在生成新一轮",
		"LANGUAGE": "语言",
		"LANGUAGE_VALUE": "语言：%s",
	},
	"hi": {
		"GAME_TITLE": "MAZE POINT",
		"BY": "द्वारा",
		"LEVEL_STATUS": "लेवल %d  |  %d / %d",
		"MOVES": "%d चालें",
		"LEVEL_CLEAR": "लेवल पूरा",
		"TOTAL_MOVES": "कुल %d / %d  |  चालें %d",
		"OPTIMAL": "सर्वोत्तम %d",
		"RETRIES": "फिर से %d",
		"NEXT": "अगला",
		"RETRY": "फिर से",
		"RUN_OVER": "रन समाप्त",
		"SCORE": "स्कोर %d",
		"LEVELS": "लेवल %d",
		"STARS": "स्टार %d",
		"PAUSED": "रुका हुआ",
		"RESUME": "जारी रखें",
		"START": "शुरू करें",
		"NEW_RUN": "नई रन",
		"END_RUN": "रन समाप्त करें",
		"INVERT": "रंग उलटें",
		"MUSIC": "संगीत",
		"SFX": "ध्वनि",
		"BEST_SCORE_NONE": "सर्वश्रेष्ठ स्कोर --",
		"BEST_SCORE": "सर्वश्रेष्ठ स्कोर %d",
		"TRY_AGAIN": "फिर कोशिश करें",
		"LOADING": "लोड हो रहा है",
		"BUILDING_RUN": "नई रन तैयार हो रही है",
		"LANGUAGE": "भाषा",
		"LANGUAGE_VALUE": "भाषा: %s",
	},
	"es": {
		"GAME_TITLE": "MAZE POINT",
		"BY": "por",
		"LEVEL_STATUS": "NIVEL %d  |  %d / %d",
		"MOVES": "%d MOVIMIENTOS",
		"LEVEL_CLEAR": "NIVEL SUPERADO",
		"TOTAL_MOVES": "TOTAL %d / %d  |  MOVS %d",
		"OPTIMAL": "OPTIMO %d",
		"RETRIES": "REINTENTOS %d",
		"NEXT": "SIGUIENTE",
		"RETRY": "REINTENTAR",
		"RUN_OVER": "RUN TERMINADO",
		"SCORE": "PUNTOS %d",
		"LEVELS": "NIVELES %d",
		"STARS": "ESTRELLAS %d",
		"PAUSED": "PAUSA",
		"RESUME": "SEGUIR",
		"START": "EMPEZAR",
		"NEW_RUN": "NUEVO RUN",
		"END_RUN": "TERMINAR RUN",
		"INVERT": "INVERTIR",
		"MUSIC": "MUSICA",
		"SFX": "EFECTOS",
		"BEST_SCORE_NONE": "MEJOR PUNTUACION --",
		"BEST_SCORE": "MEJOR PUNTUACION %d",
		"TRY_AGAIN": "INTENTA OTRA VEZ",
		"LOADING": "CARGANDO",
		"BUILDING_RUN": "PREPARANDO NUEVO RUN",
		"LANGUAGE": "IDIOMA",
		"LANGUAGE_VALUE": "IDIOMA: %s",
	},
	"ar": {
		"GAME_TITLE": "MAZE POINT",
		"BY": "بواسطة",
		"LEVEL_STATUS": "المرحلة %d  |  %d / %d",
		"MOVES": "%d حركة",
		"LEVEL_CLEAR": "تم إنهاء المرحلة",
		"TOTAL_MOVES": "المجموع %d / %d  |  الحركات %d",
		"OPTIMAL": "الأفضل %d",
		"RETRIES": "الإعادات %d",
		"NEXT": "التالي",
		"RETRY": "إعادة",
		"RUN_OVER": "انتهت الجولة",
		"SCORE": "النتيجة %d",
		"LEVELS": "المراحل %d",
		"STARS": "النجوم %d",
		"PAUSED": "متوقف",
		"RESUME": "متابعة",
		"START": "ابدأ",
		"NEW_RUN": "جولة جديدة",
		"END_RUN": "إنهاء الجولة",
		"INVERT": "عكس الألوان",
		"MUSIC": "الموسيقى",
		"SFX": "المؤثرات",
		"BEST_SCORE_NONE": "أفضل نتيجة --",
		"BEST_SCORE": "أفضل نتيجة %d",
		"TRY_AGAIN": "حاول مرة أخرى",
		"LOADING": "جار التحميل",
		"BUILDING_RUN": "يتم تجهيز جولة جديدة",
		"LANGUAGE": "اللغة",
		"LANGUAGE_VALUE": "اللغة: %s",
	},
	"fr": {
		"GAME_TITLE": "MAZE POINT",
		"BY": "par",
		"LEVEL_STATUS": "NIVEAU %d  |  %d / %d",
		"MOVES": "%d COUPS",
		"LEVEL_CLEAR": "NIVEAU TERMINE",
		"TOTAL_MOVES": "TOTAL %d / %d  |  COUPS %d",
		"OPTIMAL": "OPTIMAL %d",
		"RETRIES": "REESSAIS %d",
		"NEXT": "SUIVANT",
		"RETRY": "REESSAYER",
		"RUN_OVER": "PARTIE FINIE",
		"SCORE": "SCORE %d",
		"LEVELS": "NIVEAUX %d",
		"STARS": "ETOILES %d",
		"PAUSED": "PAUSE",
		"RESUME": "REPRENDRE",
		"START": "DEMARRER",
		"NEW_RUN": "NOUVELLE PARTIE",
		"END_RUN": "TERMINER",
		"INVERT": "INVERSER",
		"MUSIC": "MUSIQUE",
		"SFX": "EFFETS",
		"BEST_SCORE_NONE": "MEILLEUR SCORE --",
		"BEST_SCORE": "MEILLEUR SCORE %d",
		"TRY_AGAIN": "REESSAYE",
		"LOADING": "CHARGEMENT",
		"BUILDING_RUN": "PREPARATION DE LA PARTIE",
		"LANGUAGE": "LANGUE",
		"LANGUAGE_VALUE": "LANGUE : %s",
	},
	"pt_BR": {
		"GAME_TITLE": "MAZE POINT",
		"BY": "por",
		"LEVEL_STATUS": "FASE %d  |  %d / %d",
		"MOVES": "%d JOGADAS",
		"LEVEL_CLEAR": "FASE LIMPA",
		"TOTAL_MOVES": "TOTAL %d / %d  |  JOGADAS %d",
		"OPTIMAL": "OTIMO %d",
		"RETRIES": "TENTATIVAS %d",
		"NEXT": "PROXIMA",
		"RETRY": "TENTAR DE NOVO",
		"RUN_OVER": "RUN ENCERRADA",
		"SCORE": "PONTOS %d",
		"LEVELS": "FASES %d",
		"STARS": "ESTRELAS %d",
		"PAUSED": "PAUSADO",
		"RESUME": "CONTINUAR",
		"START": "COMEÇAR",
		"NEW_RUN": "NOVA RUN",
		"END_RUN": "ENCERRAR RUN",
		"INVERT": "INVERTER",
		"MUSIC": "MUSICA",
		"SFX": "EFEITOS",
		"BEST_SCORE_NONE": "MELHOR PONTUACAO --",
		"BEST_SCORE": "MELHOR PONTUACAO %d",
		"TRY_AGAIN": "TENTE DE NOVO",
		"LOADING": "CARREGANDO",
		"BUILDING_RUN": "MONTANDO NOVA RUN",
		"LANGUAGE": "IDIOMA",
		"LANGUAGE_VALUE": "IDIOMA: %s",
	},
	"de": {
		"GAME_TITLE": "MAZE POINT",
		"BY": "von",
		"LEVEL_STATUS": "LEVEL %d  |  %d / %d",
		"MOVES": "%d ZUGE",
		"LEVEL_CLEAR": "LEVEL GESCHAFFT",
		"TOTAL_MOVES": "SUMME %d / %d  |  ZUGE %d",
		"OPTIMAL": "OPTIMAL %d",
		"RETRIES": "NEUSTARTS %d",
		"NEXT": "WEITER",
		"RETRY": "NOCHMAL",
		"RUN_OVER": "RUN BEENDET",
		"SCORE": "PUNKTE %d",
		"LEVELS": "LEVEL %d",
		"STARS": "STERNE %d",
		"PAUSED": "PAUSE",
		"RESUME": "FORTSETZEN",
		"START": "START",
		"NEW_RUN": "NEUER RUN",
		"END_RUN": "RUN BEENDEN",
		"INVERT": "INVERTIEREN",
		"MUSIC": "MUSIK",
		"SFX": "SFX",
		"BEST_SCORE_NONE": "BESTWERT --",
		"BEST_SCORE": "BESTWERT %d",
		"TRY_AGAIN": "NOCH EINMAL",
		"LOADING": "LADEN",
		"BUILDING_RUN": "NEUER RUN WIRD ERSTELLT",
		"LANGUAGE": "SPRACHE",
		"LANGUAGE_VALUE": "SPRACHE: %s",
	},
	"ja": {
		"GAME_TITLE": "MAZE POINT",
		"BY": "制作",
		"LEVEL_STATUS": "レベル %d  |  %d / %d",
		"MOVES": "%d 手",
		"LEVEL_CLEAR": "レベルクリア",
		"TOTAL_MOVES": "合計 %d / %d  |  手数 %d",
		"OPTIMAL": "最短 %d",
		"RETRIES": "リトライ %d",
		"NEXT": "次へ",
		"RETRY": "リトライ",
		"RUN_OVER": "ラン終了",
		"SCORE": "スコア %d",
		"LEVELS": "レベル %d",
		"STARS": "スター %d",
		"PAUSED": "一時停止",
		"RESUME": "戻る",
		"START": "スタート",
		"NEW_RUN": "ニューラン",
		"END_RUN": "ラン終了",
		"INVERT": "色反転",
		"MUSIC": "音楽",
		"SFX": "効果音",
		"BEST_SCORE_NONE": "ベストスコア --",
		"BEST_SCORE": "ベストスコア %d",
		"TRY_AGAIN": "もう一度",
		"LOADING": "読み込み中",
		"BUILDING_RUN": "新しいランを生成中",
		"LANGUAGE": "言語",
		"LANGUAGE_VALUE": "言語: %s",
	},
	"ko": {
		"GAME_TITLE": "MAZE POINT",
		"BY": "제작",
		"LEVEL_STATUS": "레벨 %d  |  %d / %d",
		"MOVES": "%d 수",
		"LEVEL_CLEAR": "레벨 클리어",
		"TOTAL_MOVES": "합계 %d / %d  |  이동 %d",
		"OPTIMAL": "최적 %d",
		"RETRIES": "재시도 %d",
		"NEXT": "다음",
		"RETRY": "재시도",
		"RUN_OVER": "런 종료",
		"SCORE": "점수 %d",
		"LEVELS": "레벨 %d",
		"STARS": "별 %d",
		"PAUSED": "일시정지",
		"RESUME": "계속",
		"START": "시작",
		"NEW_RUN": "새 런",
		"END_RUN": "런 종료",
		"INVERT": "색 반전",
		"MUSIC": "음악",
		"SFX": "효과음",
		"BEST_SCORE_NONE": "최고 점수 --",
		"BEST_SCORE": "최고 점수 %d",
		"TRY_AGAIN": "다시 시도",
		"LOADING": "불러오는 중",
		"BUILDING_RUN": "새 런 생성 중",
		"LANGUAGE": "언어",
		"LANGUAGE_VALUE": "언어: %s",
	},
}

static func get_languages() -> Array:
	return LANGUAGES


static func has_language(code: String) -> bool:
	return STRINGS.has(code)


static func get_text(language_code: String, key: String) -> String:
	var localized_language: String = language_code if STRINGS.has(language_code) else DEFAULT_LANGUAGE
	var localized_table: Dictionary = STRINGS.get(localized_language, {})
	if localized_table.has(key):
		return String(localized_table[key])
	var fallback_table: Dictionary = STRINGS.get(DEFAULT_LANGUAGE, {})
	return String(fallback_table.get(key, key))


static func get_language_name(language_code: String) -> String:
	for entry_variant in LANGUAGES:
		var entry: Dictionary = entry_variant
		if String(entry.get("code", "")) == language_code:
			return String(entry.get("name", language_code))
	return language_code
